### ISSUE TITLE
Color_MIP_Mask_Search: NullPointerException launch error

### ISSUE THREAD

**Issue by neilzhang-ucsb** [JaneliaSciComp/ColorMIP_Mask_Search#6]
Dear Hideo,
I'm trying to set up colormip search in my computer but had some error during the plugin launch.

I'm using the latest version of Fiji. I also tried on another computer (also win 10) and it is the same problem. Could you please help me have a look? Thanks!

(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 101MB of 12129MB (<1%)

java.lang.NullPointerException
	at Color_MIP_Mask_Search.setup(Color_MIP_Mask_Search.java:162)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:48)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

Best,
Neil

**Comment by neilzhang-ucsb** [comment]
![image](https://user-images.githubusercontent.com/36348097/91651899-f529f780-ea46-11ea-8ca1-3b2ba70ae03c.png)

**Comment by HideoOtsuna** [comment]
Hi Neil,

You need to open at least 2 color depth MIPs before run the plugin. One is searching mask, the other is stack of Color Depth MIP (dataset for search).

Thank you,
Hideo

**Comment by neilzhang-ucsb** [comment]
Hi Hideo,

Thanks for your quick response. It is working now.

Best,
Neil
